[package]
name = "conc-map-bench"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[dependencies]
bustle = { git = "https://git.nebulanet.cc/Acrimon/bustle-temp-fix.git" }
tracing-subscriber = "0.2.2"
num_cpus = "1.12.0"
fxhash = "0.2.1"
chashmap = "2.2.2"
contrie = "0.1.4"
flurry = "0.2.0"
dashmapv3 = { version = "3.5.1", package = "dashmap" }
dashmap-experimental = { git = "https://github.com/xacrimon/dashmap.git", rev = "caa890df3dd456cbda306f63e81aec1f7e8340aa", package = "dashmap" }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
