[package]
name = "conc-map-bench"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[dependencies]
bustle = "0.4.1"
tracing-subscriber = "0.2.3"
num_cpus = "1.12.0"
fxhash = "0.2.1"
chashmap = "2.2.2"
contrie = "0.1.4"
flurry = "0.2.1"
dashmapv3 = { version = "3.9.1", package = "dashmap" }
dashmap-experimental = { git = "https://github.com/xacrimon/dashmap.git", rev = "736c4fa6872b357217f19853456eedc2e56f6e7b", package = "dashmap", features = ["nightly"] }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
