[package]
name = "conc-map-bench"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[dependencies]
bustle = "0.4.1"
tracing-subscriber = "0.2.4"
num_cpus = "1.13.0"
fxhash = "0.2.1"
chashmap = "2.2.2"
contrie = "0.1.4"
flurry = "0.3.0"
dashmap = { git = "https://github.com/xacrimon/dashmap.git", rev = "cc9fd11ffb15695c5c9b79223fd875f6df4357db" }
crossbeam-epoch = "0.8"
crossbeam-epoch-old = { package = "crossbeam-epoch", version = "0.7" }

[profile.release]
codegen-units = 1
panic = "abort"
lto = true
