[package]
name = "conc-map-bench"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[dependencies]
bustle = "0.3.2"
tracing-subscriber = "0.2.2"
num_cpus = "1.12.0"
fxhash = "0.2.1"
chashmap = "2.2.2"
contrie = "0.1.4"

[[bench]]
name = "read_heavy"
harness = false
