[package]
name = "conc-map-bench"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[dependencies]
bustle = "=0.3.2"
tracing-subscriber = "0.2.2"
num_cpus = "1.12.0"
fxhash = "0.2.1"
chashmap = "2.2.2"
contrie = "0.1.4"
flurry = "0.1.0"
dashmapv3 = { version = "3.5.1", package = "dashmap" }
dashmap-experimental = { git = "https://github.com/xacrimon/dashmap.git", rev = "523aa5e140ec941e6611534cbe4e42c9f0f35e5b", package = "dashmap" }

[[bench]]
name = "read_heavy"
harness = false

[[bench]]
name = "insert_heavy"
harness = false

[[bench]]
name = "update_heavy"
harness = false
